### ISSUE TITLE
[To-Do before 0.1.0 release] Current list of open tasks before 0.1.0 can be released.

### ISSUE THREAD

**Issue by Anuril** [FOSSBilling/Proxmox#26]
This issue is intended as a collection of known issues that will need to be fixed before 0.1.0

Template Management System #13 
- [x] New VM / LXC templates can't be saved, only the "Activate" button does something.
- [x] When creating a new vm template, new storage can't be added / saved.
- [x] Storage for VM / LXC templates can't be updated
- [x] VM / LXC templates can't be set active.
- [ ] Removeable storage needs to be loaded from VM Host and be able to be added.
    - [ ] Find a way to reconcile different iso contents on different servers.
- [ ] Network configuration for VM / LXC templates
- [ ] Details of template VMs can't be viewed.
     - These vm templates need to be able to be set up with cloud init isos. => Need solution for that
- [ ] Functionality to create a vm from an order _(Kinda sorta works)_

IPAM #12 
- [x] Subnet calculation needs to be made more sturdy, so f.ex when you change the CIDR IP, it will automatically change Network & Broadcast, not only after you move the Size slider.
- [ ] IPAM Settings: Automatically create VLAN & IP range per customer
- [ ] IPAM Settings: IP adress range types for automatic creation, and for manual creation

Other Issues
- [x] Replace AJAX in Product configuration and VM / LXC template pages with Fossbilling native JS API wrapper
- [x] Can't yet add storages classes in the settings.
- [x] Storages that have size 0 break different pages (Overview, edit Storage) (Fixed in code, not yet in repo) 
- [ ] Preparation for the Permissions rework of FB 0.6.0 (https://github.com/FOSSBilling/FOSSBilling/pull/1545)

**Comment by BelleNottelling** [comment]
> Encrypt / Decrypt the authentication information using FBs built-in crypto methods

We might want to look at these in-dept and ensure they are implemented in a way that's not flawed. They are untouched from BoxBilling code as far as I know so it might be in need of a rewrite. (Hopefully not, it's already in use to save module configs)

**Comment by Anuril** [comment]
They look pretty sound, the salt from the config file is used as symmetric key. https://github.com/FOSSBilling/FOSSBilling/blob/3d7132321a8def4373a5138cdbc7789e094ecd2c/src/library/Box/Crypt.php#L34

Might not be the longest key, but oh well.

**Comment by ShangTianYa** [comment]
拜托快上线啊

**Comment by ShangTianYa** [comment]
请问还有什么替代开源方案能实现FOSSBilling对接promox吗？

**Comment by ShangTianYa** [comment]
[录屏 2024-10-17 01-07-14.webm](https://github.com/user-attachments/assets/72fd50ed-86ce-4853-a7ae-77b10d3e13f3)

我没有看到proxmox插件啊。权限也有检查没有问题，请问该如何启用？
![image](https://github.com/user-attachments/assets/d1bb4056-812e-4f94-a919-5a0abb237b4b)

**Comment by Anuril** [comment]
> 2024-10-17.01-07-14.webm
> 
> 我没有看到proxmox插件啊。权限也有检查没有问题，请问该如何启用？ ![image](https://private-user-images.githubusercontent.com/69330243/377319493-d1bb4056-812e-4f94-a919-5a0abb237b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzE0NjAsIm5iZiI6MTcyOTIzMTE2MCwicGF0aCI6Ii82OTMzMDI0My8zNzczMTk0OTMtZDFiYjQwNTYtODEyZS00Zjk0LWE5MTktNWEwYWJiMjM3YjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA1NTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OWEyMjEwZjc4YjkwNzFlZTIxMzc3NDc3NzhlYmM0YWI5OGM2MjU2MWVkZjlhMjhlNzU2MTIxODY0YzdkYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eM6XFQP7xG2dFp07SYrYs2xZIGnMBjSwzyTRS_RIwq4)

It is not working yet. No vm creation process.

To test how far it is - use this https://github.com/Anuril/Proxmox/releases/download/v0.1.0-alpha0/Serviceproxmox.zip 

Contents of the Serviceproxmox zip file need to be under modules/

So 

/var/www/modules/Serviceproxmox/ has to contain 

![grafik](https://github.com/user-attachments/assets/0e7396dc-f2ad-4c8d-be88-62317e9477c3)

**Comment by quadrix-hd** [comment]
Is this module for Proxmox dead?
